### ISSUE TITLE
State.js errors, including ERR_INVALID_CALLBACK 

### ISSUE THREAD

**Issue by jaydisc** [ztalbot2000/homebridge-cmd4#10]
Fascinating plugin! I'm keen to see if I can create some fake, triggerable Motion Sensors in order to get some push notifications.

Have installed, then installed State.js, and plucked the relevant config for the devices out of config.json. It all initialises without error, but as soon as I view anything in Home.app, homebridge try to run State.js, and fails continuously with errors like these:

    [7/24/2018, 7:39:09 PM] [Cmd4] Cmd4 getGeneric On function for: My_OnOff_Light cmd: node .homebridge/Cmd4Scripts/State.js Get 'My_OnOff_Light' 'On' failed.
    [7/24/2018, 7:39:09 PM] [Cmd4] { Error: Command failed: node .homebridge/Cmd4Scripts/State.js Get 'My_OnOff_Light' 'On'
    internal/modules/cjs/loader.js:596
        throw err;
        ^
    
    Error: Cannot find module '/.homebridge/Cmd4Scripts/State.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
        at Function.Module._load (internal/modules/cjs/loader.js:520:25)
        at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
        at startup (internal/bootstrap/node.js:240:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
    
        at ChildProcess.exithandler (child_process.js:291:12)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:961:16)
        at Socket.stream.socket.on (internal/child_process.js:380:11)
        at Socket.emit (events.js:182:13)
        at Pipe._handle.close (net.js:595:12)
      killed: false,
      code: 1,
      signal: null,
      cmd:
       'node .homebridge/Cmd4Scripts/State.js Get \'My_OnOff_Light\' \'On\'' }
    [7/24/2018, 7:39:09 PM] [Cmd4] 
    [7/24/2018, 7:39:09 PM] [Cmd4] internal/modules/cjs/loader.js:596
        throw err;
        ^
    
    Error: Cannot find module '/.homebridge/Cmd4Scripts/State.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
        at Function.Module._load (internal/modules/cjs/loader.js:520:25)
        at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
        at startup (internal/bootstrap/node.js:240:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)

The error is seemingly "cannot find module". So, I tried just running State.js by itself in Terminal from the homebridge user's home directory, but I get a different error:

    $ node .homebridge/Cmd4Scripts/State.js Set 'My_ContactSensor' 'ContactSensorState' 0
    fs.js:141
        throw new ERR_INVALID_CALLBACK();
        ^
    
    TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
        at makeCallback (fs.js:141:11)
        at Object.mkdir (fs.js:720:16)
        at Object.<anonymous> (/Users/anyone/.homebridge/Cmd4Scripts/State.js:77:4)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
        at Module.load (internal/modules/cjs/loader.js:612:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
        at Function.Module._load (internal/modules/cjs/loader.js:543:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
        at startup (internal/bootstrap/node.js:240:19)

**Comment by ztalbot2000** [comment]
Hi Jason,

  I think the problem you are seeing is relative to the path you have
given.

In the first case The error says," Error: Cannot find module  /.homebridge
..."
The starting "/"  would mean from the root directory, which I am sure your
account is not.

In the second case you are trying you are not in your home directory, but I
think you are in .homebridge Cmd4Scripts.   So once again you a similiar
path error.

Try the commands:
cd
ls .homebridge/Cmd4Scripts/State.js
node .homebridge/Cmd4Scripts/State.js Get My_OnOff_Light On

A breakdown of those commands are:
-Change to your home directory
-List the file State.jsin the directory .homebridge/Cmd4Scripts from your
current directory
-execute node passing the file .homebridge/Cmd4Scripts/State.j, which is
also relative to where you are in your home directory.

I think what you really wanted to try was:
node State.js
while you happened to be in the .homebridge/Cmd4Scripts directory.

I hope this helps you.  If not send me your next output and the contents of
your config.json file.

Take care,
John Talbot

**Comment by jaydisc** [comment]
Yes, I agree the leading slash would indicate it's looking at from the root of the drive, but I have not specified that anywhere, thus cannot remove it. I'm using the default paths copies from the sample config.json.

But to me, it seems the first problem is just getting State.js working, which I can't. When I did that test, unfortunately, I was in the home directory, and everything was seemingly in the right places. Here is a bit more detail:

    home:~ anyone$ pwd
    /Users/anyone
    home:~ anyone$ ls -l .homebridge/Cmd4Scripts/State.js 
    -rwx------  1 anyone  staff  179002 Jul 24 19:27 .homebridge/Cmd4Scripts/State.js
    home:~ anyone$ node .homebridge/Cmd4Scripts/State.js Get My_OnOff_Light On
    fs.js:141
        throw new ERR_INVALID_CALLBACK();
        ^
    
    TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
        at makeCallback (fs.js:141:11)
        at Object.mkdir (fs.js:720:16)
        at Object.<anonymous> (/Users/anyone/.homebridge/Cmd4Scripts/State.js:77:4)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
        at Module.load (internal/modules/cjs/loader.js:612:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
        at Function.Module._load (internal/modules/cjs/loader.js:543:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
        at startup (internal/bootstrap/node.js:240:19)
    home:~ anyone$ 

And here is.json: 
[config.json.zip](https://github.com/ztalbot2000/homebridge-cmd4/files/2227549/config.json.zip)

I've also attached homebridge's log: 
[homebridge.log.zip](https://github.com/ztalbot2000/homebridge-cmd4/files/2227556/homebridge.log.zip)

**Comment by jaydisc** [comment]
I've just replaced the relative paths in config.json with full paths, and now homebridge is giving the same errors I get when I try to run State.js manually:

    [7/25/2018, 8:31:25 PM] [Cmd4] Cmd4 getGeneric Brightness function for: My_Dimmable_Light cmd: node /Users/anyone/.homebridge/Cmd4Scripts/State.js Get 'My_Dimmable_Light' 'Brightness' failed.
    [7/25/2018, 8:31:25 PM] [Cmd4] { Error: Command failed: node /Users/anyone/.homebridge/Cmd4Scripts/State.js Get 'My_Dimmable_Light' 'Brightness'
    fs.js:141
        throw new ERR_INVALID_CALLBACK();
        ^
    
    TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
        at makeCallback (fs.js:141:11)
        at Object.mkdir (fs.js:720:16)
        at Object.<anonymous> (/Users/anyone/.homebridge/Cmd4Scripts/State.js:77:4)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
        at Module.load (internal/modules/cjs/loader.js:612:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
        at Function.Module._load (internal/modules/cjs/loader.js:543:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
        at startup (internal/bootstrap/node.js:240:19)
    
        at ChildProcess.exithandler (child_process.js:291:12)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:961:16)
        at Socket.stream.socket.on (internal/child_process.js:380:11)
        at Socket.emit (events.js:182:13)
        at Pipe._handle.close (net.js:595:12)
      killed: false,
      code: 1,
      signal: null,
      cmd:
       'node /Users/anyone/.homebridge/Cmd4Scripts/State.js Get \'My_Dimmable_Light\' \'Brightness\'' }
    [7/25/2018, 8:31:25 PM] [Cmd4] 
    [7/25/2018, 8:31:25 PM] [Cmd4] fs.js:141
        throw new ERR_INVALID_CALLBACK();
        ^
    
    TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
        at makeCallback (fs.js:141:11)
        at Object.mkdir (fs.js:720:16)
        at Object.<anonymous> (/Users/anyone/.homebridge/Cmd4Scripts/State.js:77:4)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
        at Module.load (internal/modules/cjs/loader.js:612:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
        at Function.Module._load (internal/modules/cjs/loader.js:543:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
        at startup (internal/bootstrap/node.js:240:19)

**Comment by ztalbot2000** [comment]
Thanks for the information.  I had to know if things were installed
properly. I never know what the persons skill level is. You seem to be very
knowledgeable.

I will be looking carefully to what you sent me and get back to you shortly.

John Talbot

**Comment by ztalbot2000** [comment]
I tried mine and it returned 100 as expected.
Looking at the traceback though is a little disturbing.  It clearly has a
problem trying to make the directory
"$HOME/.homebridge/Cmd4Scripts/Cmd4States"
It is not really making the directory but having issues with fs.js and the
mkdir function.
I googled python fs ERR_INVALID_CALLBACK and there could possibly be an
issue with mkdir function requiring a callback that on my platform does not
cause an issue.
Have you changed State.js in any way so that var fs = require('fs');   is
missing?  You will probably say no so
my second question is what platform are you running on?  i.e Linux/OSX/Win
   ?
There may be still an issue with State.js on different platforms.  I will
see what I can do but the answers to the above questions would be useful.
Could you also try mkdir .homebridge/Cmd4Scripts/Cmd4States   and then see
what happens.
Thanks,
John

**Comment by ztalbot2000** [comment]
Jason,

  Could you also get the version of python you are running?
python -V

I'm running 2.7.10.  I think python 3 has extra checks for fs.mkdir

**Comment by ztalbot2000** [comment]
fix coming.  it's a node.js thing on platforms.  I would still like to know
what platform you are on.

**Comment by ztalbot2000** [comment]
I put try catch blocks around all the filesystem calls.  I tested all the
possible cases of the directory not existing, file read/write access, the
whole shebang.  Can you replace the .homebridge/Cmd4Scripts/State.js with
the one attached and let me know if it solves your problem before I release
it.
You need to rename the attached file from State to State.js because gmail
thinks it is a malicious file.

**Comment by jaydisc** [comment]
Hi, it looks like you're replying to Issues via email? I'm not seeing any attachment. Sorry for leaving out the platform stuff.

macOS High Sierra 10.13.5
node and npm installed via homebrew:

    $ node -v
    v10.7.0
    $ npm -v
    6.2.0
    $ python -V
    Python 2.7.15

Thanks for looking into this.

**Comment by ztalbot2000** [comment]
Hi,

  It is l3 A.M..  I pushed it to GitHub.  Please pull it from there and let
me know what happens.

Night,
John

**Comment by ztalbot2000** [comment]
I was able to duplicate the issue with the latest node.js and the solution I sent you resolved the issue.
I have committed the changes and published them to v1.2.3.
If you have further problems, contact me at ztalbot2000@gmail.com

**Comment by jaydisc** [comment]
Sorry for late reply. Forgot to hit submit last night....

Thank you very much. It looks good. I can run it manually, and see the updated contents in Cmd4Scripts/Cmd4States.

It's also looking better in homebridge, which seems to be working, but it doesn't seem to log transactions? Is that right? With the other plugins I'm using I see entries like this:

    [7/26/2018, 7:46:40 PM] [WeMo Platform] WeMo Display Cabinets - Set state: Off
    [7/26/2018, 7:46:42 PM] [WeMo Platform] WeMo Display Cabinets - Set state: On
    [7/26/2018, 7:47:28 PM] [Office Motion] Setting switch to false

**Comment by ztalbot2000** [comment]
I have seen those messages too.  There are different debug levels that will
do that are built into homebridge itself.  If you really wanted to, edit
the index.js file in /usr/local.  I have mine commented out.

Ttfn,
John

**Comment by jaydisc** [comment]
Perfect! Thanks again.
