### ISSUE TITLE
disable satecmd check on startup[Support]

### ISSUE THREAD

**Issue by crbyxwpzfl** [ztalbot2000/homebridge-cmd4#116]
**Describe Your Problem:**
I want to open a ssh session and call a remote python script via the sate_cmd
```json
...
"state_cmd": "ssh user@ip python3 \"/home/pi/spinala/tisch.py\"
...
```
this results in an error when I start homebridge
```shell
 Error: The file: ""/home/pi/spinala/tisch.py"" does not exist, It is highly likely the state_cmd will fail. Hint: Do not use wildcards that would normally be expanded by a shell.
    at Cmd4Accessory.validateStateCmd (/usr/local/lib/node_modules/homebridge-cmd4/Cmd4Accessory.js:1270:22)
    at Cmd4Accessory.parseConfig (/usr/local/lib/node_modules/homebridge-cmd4/Cmd4Accessory.js:1752:15)
    at new Cmd4Accessory (/usr/local/lib/node_modules/homebridge-cmd4/Cmd4Accessory.js:254:12)
    at /usr/local/lib/node_modules/homebridge-cmd4/Cmd4Platform.js:543:25
    at Array.forEach (<anonymous>)
    at Cmd4Platform.discoverDevices (/usr/local/lib/node_modules/homebridge-cmd4/Cmd4Platform.js:406:58)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-cmd4/Cmd4Platform.js:120:15)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
```
is there a simple way to disable this check?
this is just a minor issue and probably very specific. I can work around this if there is no easy way to disable this check.
any way I really love your plugin and you already heled me a bunch of times! I am very thankfull for your effort and time!

**Environment:**

* **Node.js Version**: v16.13.0
* **NPM Version**: 8.1.0
* **Homebridge Version**: 1.3.5
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by crbyxwpzfl** [comment]
ok I solved it for my specific case by commenting out parts of the `validateStateCmd()` in `Cmd4Accessory.js` so it always returns `ture`.  
```java
validateStateCmd( state_cmd )
{
/*
...
*/
return true
}
```
But I dont feel confident about this becasue I dont know if this causes other issues. 
anyway feel free to close this.

**Comment by ztalbot2000** [comment]
Hi,

I have done just that too.  Sorry, I'm trying to get something in at the
same time.  The fix should be later today.  Sorry for the late response.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi,

   I just release v6.0.1 that did exactly what you wanted.  That code has been there since the beginning and was never a really good thing to do.
Sometimes trying to help people with code like the validateStateCmd function has brought me more trouble than it was worth.

Enjoy Cmd4,
John Talbot

**Comment by crbyxwpzfl** [comment]
wow thank you again for your quick help! I appreciate this very much!

**Comment by ztalbot2000** [comment]
Hi,

Your quite welcome.


John Talbot
