### ISSUE TITLE
I am getting errors when I try to run this program

### ISSUE THREAD

**Issue by nbaddorf** [ztalbot2000/homebridge-cmd4#17]
I have homebridge working and all the state.js stuff working but I am getting some errors when I run it. Here they are.

[2/24/2019, 6:06:07 PM] Loaded config.json with 1 accessories and 1 platforms.
[2/24/2019, 6:06:07 PM] ---
[2/24/2019, 6:06:07 PM] Plugin /usr/local/lib/node_modules/homebridge-cmd4 requi4.0.0. You may need to upgrade your installation of Node.
[2/24/2019, 6:06:07 PM] Loaded plugin: homebridge-cmd4
[2/24/2019, 6:06:07 PM] Registering accessory 'homebridge-cmd4.Cmd4'
[2/24/2019, 6:06:07 PM] Registering platform 'homebridge-cmd4.Cmd4'
[2/24/2019, 6:06:07 PM] ---
[2/24/2019, 6:06:07 PM] Loading 1 platforms...
[2/24/2019, 6:06:07 PM] [Cmd4] Initializing Cmd4 platform...
[2/24/2019, 6:06:07 PM] [Cmd4] Cmd4:Fetching config.json devices.
[2/24/2019, 6:06:07 PM] [Cmd4] Cmd4:Found PS4
[2/24/2019, 6:06:07 PM] [Cmd4] Initializing platform accessory 'PS4'...
[2/24/2019, 6:06:07 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server.str.replace.Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.str.replace.Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

I dont know how to fix it. Please help.

**Comment by ztalbot2000** [comment]
Hi,

  I would start with the third line in the log file which says node seems
out of date.  Look into upgrading npm first. See the NPM documentation on
how to do this.  If you still have issues, send me the platform you are
running on, npm version, your config.json file and any private script you.
Have crated.



TTFN,
John

**Comment by nbaddorf** [comment]
thanks for the quick response! so I tried to update node to different versions like 10.15.1, 5.10.0 and some others. when I run node -v it shows they are the right versions. however when I run homebridge I get this:

pi@raspberrypi:~ $ homebridge
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/node_modules/bindings/bindings.js:119
        throw e;
        ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
pi@raspberrypi:~ $ 


I think there is a problem with node and homebridge. Homebridge still launches when I have node 4.0.0 but then it crashes when it loads the cmd4 plugin. I think node 4 will work but I don't know. I am running this on a raspberry pi 3 but have tryed it on  a mac book and also not been able to get cmd4 working.

**Comment by nbaddorf** [comment]
Also I forgot but here is my config.json:


{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

        "accessories": [{

        }],

        "platforms": [{
                "platform": "Cmd4",
                "name": "Cmd4",
                "accessories": [{
                        "type": "Switch",
                        "name": "PS4",
                        "on": false,
                        "state_cmd": "bash .homebridge/Cmd4Scripts/PS4.sh",
                        "polling": true,
                        "interval": 5,
                        "timeout": 2000


                }]
        }]
}




And I am running the PS4 test script

**Comment by ztalbot2000** [comment]
I am just about to have lunch.  Are you using Raspbian?  What version and I
will try it on mine afterwards.

John

**Comment by nbaddorf** [comment]
Yes I am using Raspbian and I think this is it

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by nbaddorf** [comment]
Oh, I see now that cmd4 wants a newer version of node not homebridge. How do I get a newer version of node without making homebridge not work?

**Comment by nbaddorf** [comment]
So I think that my pi doesn't like npm. I can use commands like npm rebuild when i am using node 4 but as soon as I use node 10 npm stops working and gives me errors. I am noting that node 4 is the only thing working. everything else just gives me errors.

**Comment by ztalbot2000** [comment]
I am currently downloading the latest Raspbian Stretch. It will take
another half hour to put it on a flash drive.

Have you thought of uninstalling nom and re-installing it?
You should be using apt-get to do this.

ttfn,
John

**Comment by ztalbot2000** [comment]
Sorry, uninstalling nom

**Comment by ztalbot2000** [comment]
sp. npm

**Comment by nbaddorf** [comment]
I tried to uninstall npm but in all other versions other that node 4 and it says that there are no versions of npm to uninstall. I ran someones code to update both and I think it worked but only for root not pi. I am wondering if I should ether reinstall rasbean or delete homebridge or something

**Comment by nbaddorf** [comment]
I seem to finally have updated both npm and node but homebridge still gives me errors. Should I uninstall homebridge? if so will it delete npm and node?

**Comment by ztalbot2000** [comment]
Npm should be installed with:
sudo apt-get install nodejs npm

if you need to re install it google:
 *how to* *reinstall* npm on raspbian
<https://www.google.com/search?client=safari&rls=en&q=how+to+reinstall+npm+on+raspbian&spell=1&sa=X&ved=0ahUKEwi4-_Hw4dfgAhWG7oMKHY0kARYQkeECCCsoAA>


Once that is done, home bridge is installed with

# --unsafe-perm fixes the utime error on .node-gyp

sudo npm install --unsafe-perm --verbose -g homebridge

Then install homebridge-cmd4

sudo npm install -g homebridge-cmd4



I prefer using -g to install it globally so that any daemons that will be
run from root at startup and stuff is automatically in your path.

I just flashed my SD card and it is currently updating raspbian before it
lets me in.

ttfn,
John Talboty

**Comment by nbaddorf** [comment]
Before I got this message, I uninstalled homebridge and reinstalled it but not in the -unsafe way and now npm and node are working but i am getting the original errors except the node version being to old. Do I kneed to find out how to uninstall homebridge and install it like you said to?

**Comment by nbaddorf** [comment]
My new error message is : 


pi@raspberrypi:~ $ homebridge
[2/25/2019, 4:18:34 PM] Loaded config.json with 1 accessories and 1 platforms.
[2/25/2019, 4:18:34 PM] ---
[2/25/2019, 4:18:34 PM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-cmd4' since we already loaded the same plugin from '/home/pi/n/lib/node_modules/homebridge-cmd4'.
[2/25/2019, 4:18:34 PM] Loaded plugin: homebridge-cmd4
[2/25/2019, 4:18:34 PM] Registering accessory 'homebridge-cmd4.Cmd4'
[2/25/2019, 4:18:34 PM] Registering platform 'homebridge-cmd4.Cmd4'
[2/25/2019, 4:18:34 PM] ---
[2/25/2019, 4:18:35 PM] Loaded plugin: homebridge-script2
[2/25/2019, 4:18:35 PM] Registering accessory 'homebridge-script2.Script2'
[2/25/2019, 4:18:35 PM] ---
[2/25/2019, 4:18:36 PM] Loading 1 platforms...
[2/25/2019, 4:18:36 PM] [Cmd4] Initializing Cmd4 platform...
[2/25/2019, 4:18:36 PM] [Cmd4] Cmd4:Fetching config.json devices.
[2/25/2019, 4:18:36 PM] [Cmd4] Cmd4:Found PS4
[2/25/2019, 4:18:36 PM] [Cmd4] Initializing platform accessory 'PS4'...
[2/25/2019, 4:18:36 PM] Loading 1 accessories...
/home/pi/n/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/home/pi/n/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/home/pi/n/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/home/pi/n/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/home/pi/n/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/home/pi/n/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


Also the message about skiping the cmd4 file is because it was finding it in a different directory i think and when I installed it again it said that it was skiping it from a different directory

**Comment by nbaddorf** [comment]
some how after all my messing with npm and node I now have some of my homebridge files in ~/n/bin and my configs in ~.homebridge It still seems to be fine but I don't know

**Comment by ztalbot2000** [comment]
Hi,

   Well it has been a while since I installed node.js from scratch.
Especially on Raspbian.  I'm on a Mac most of the time.  It does seem that
apt-get installs a very old npm. npm install -g nodejs results in version 8
that homebridge does not like.  Maybe that is why things are working for
you know.  The latest seems the best.  Unfortunately that is all for me
today.  I'll try again tomorrow to get a definitive answer.

ttfn,
John

**Comment by ztalbot2000** [comment]
So I have completed installing homebridge on Raspbian Stretch Lite.  What
great fun!  I did find an issue on my end, but mainly the  problem is with
configure npm to install homebridge properly.  Here are my notes on how to
install it.

Raspbian Stretch installs old version (8) using apt-get

======================================================

sudo vim /etc/apt/sources.list

## Add the two following lines to the source list, commentiing out the
others and save the file

deb https://deb.nodesource.com/node_9.x stretch main

deb-src https://deb.nodesource.com/node_9.x stretch main


Update sources or you will not be able to download npm

======================================================

sudo apt-get update


Check what will be installed. (It should return >=8.11.1

========================================================

apt-cache policy nodejs


Install nodejs and npm

======================

sudo apt-get install nodejs npm


Check versions of node and npm

==============================

node -v   (Should return >=v9.11.2

npm -v    (Should return >=5.6.0


Install homebridge

==================

sudo npm install -g --unsafe-perm homebridge

sudo npm install -g --unsafe-perm homebridge-cmd4

The issue I did find on my end is that the config.json file I have has in
it another platform and that being homebridge-config-ui
This can either be resolved directly by:
sudo npm install -g --unsafe-perm homebridge-config-ui
or removing the platform "config" from the .homebridge config.json file.

I will push out tomorrow an update that has the offending lines in the
config.json file removed.  They are there because I use this module to
restart homebridge from a web browser via the homebridge-config-ui module.

After this, I had no issues.  All worked from IOS Home and Eve as
documented.

ttfn,
John Talbot

**Comment by nbaddorf** [comment]
Ok, thanks for the documentation. I did what it said and I think the installing worked. I did try to run homebridge and it still gave me errors but I think you said that you would update the cmd 4 plugin to make that stop.

**Comment by ztalbot2000** [comment]
I am working on the changes now.  I appreciate the feedback.  It makes it
all easier for the next person.

I will let you know when it is done

TTFN,
John

**Comment by nbaddorf** [comment]
I am wondering if I am not having a problem with cmd4 but with homebridge now, because I am getting the error but I might be rong: 


[2019-2-27 13:43:14] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

**Comment by ztalbot2000** [comment]
That is a homebridge issue, actually neither. It is an install issue.  I
was dealing with another person and I gave hime these notes for installing
homebridge on Raspbian,

Raspbian Stretch installs old version (8) using apt-get

======================================================

sudo vim /etc/apt/sources.list

## Add the two following lines to the source list, commentiing out the
others and save the file

deb https://deb.nodesource.com/node_9.x stretch main

deb-src https://deb.nodesource.com/node_9.x stretch main


Update sources or you wil not be able to download npm

======================================================

sudo apt-get update


Check what will be installed. (It ahould return >=8.11.1

========================================================

apt-cache policy nodejs


Install nodejs and npm

======================

sudo apt-get install nodejs npm


Check versions of node and npm

==============================

node -v   (Should return >=v9.11.2

npm -v    (Should return >=5.6.0


Install homebridge

==================

sudo npm install -g --unsafe-perm homebridge

sudo npm install -g --unsafe-perm homebridge-cmd4



gotta go at the moment

**Comment by nbaddorf** [comment]
but I already did this and it didnt work. Do I kneed to reinstall Raspbian and then do it?

**Comment by ztalbot2000** [comment]
What did you get for the versions of node and npm?

You should not have to reinstall Raspbian

John

**Comment by nbaddorf** [comment]
Nothing changed. I have 10.15.1 for node and 6.8.0 for npm.

**Comment by ztalbot2000** [comment]
Let me jut try some stuff and i will get back to you tomorrow

John

**Comment by nbaddorf** [comment]
ok thanks

**Comment by ztalbot2000** [comment]
Hi,

  I'm still working on my documentation so have yet to update the
homebridge-cmd4 module officially.
I did find out that it seems that in Raspbian Stretch the latest version of
npm is included with node.js so you do not install it separately.  Here are
the rewritten notes:


Raspbian Stretch (2018-11-13-raspbian-stretch-full.img)

has old version (v8.11.1) and no npm by default

1) Update system packages

sudo apt-get update


2) Update installed  packages

sudo apt-get dist-upgrade


apt-get node.js npm would install npm version 1.4.21 and result in the
error:

Os.tmpDir() is depricated.


3) Add the two following lines to the top of the source list, commentiing
out the others and save the file

sudo vim /etc/apt/sources.list


deb https://deb.nodesource.com/node_9.x stretch main

deb-src https://deb.nodesource.com/node_9.x stretch main


4) Update sources or you wil not be able to download npm

sudo apt-get update


5) Check what will be installed. (It ahould return >=8.11.1

apt-cache policy nodejs


6) Remove old packages

sudo apt-get remove nodejs npm


7) Install nodejs (v9 install npm)

sudo apt-get install nodejs


8) Check versions of node and npm

node -v   (Should return >=v9.11.2

npm -v    (Should return >=5.6.0


9) Install homebridge

sudo npm install -g --unsafe-perm homebridge

sudo npm install -g --unsafe-perm homebridge-cmd4


I hope this helps you,

John Talbot

**Comment by nbaddorf** [comment]
So you want me to install raspbean on the same sd card and try these steps?

**Comment by ztalbot2000** [comment]
I  sent you the complete steps as I will be putting in my cocumentation.
You only need to remove node.js and npm, then install just node.js as the
latest has npm with it.


John

**Comment by ztalbot2000** [comment]
I just pushed out 1.2.7
Mainly the documentation was changed, but I did verify the Raspbian Stretch
install as well as an example bash PS4.sh script.

ttfn,
John Talbot
