### ISSUE TITLE
"No Response" in Home app

### ISSUE THREAD

**Issue by rykermorgan** [ztalbot2000/homebridge-cmd4#22]
I'm trying to get a door sensor set up by using data returned from the py-august api for my August door locks. When I run the script in my shell I correctly get a 1 or 0 for `open` or `closed` state. But, when I add it to my config.json the Home app shows the device with a "No Response" error.

Here's my the portion of my config.json file for the door sensor:
``` json
   {
      "platform": "Cmd4",
      "name": "Cmd4",
      "accessories":
      [
        {
          "type": "Door",
          "name": "Front Door",
          "currentPosition": 0,
          "targetPosition": 0,
          "positionState": 0,
          "stateChangeResponseTime": 3,
          "state_cmd": "python ~/.homebridge/Cmd4Scripts/front_door_state.py"
        }
      ]
    }
```

Here's the python script returning the state values:
``` python
#!/home/pi/berryconda3/bin/python

import sys
from august.api import Api
from august.authenticator import (
    Authenticator, AuthenticationState, ValidationResult)
import requests


user_name = '<PHONE NUMBER>'
password = '<PASSWORD>'

use_session = True
combine_status = True

api = Api(timeout=20)
authenticator = Authenticator(api, "phone", user_name, password,
                              access_token_cache_file=".august.conf")

authentication = authenticator.authenticate()


locks = api.get_operable_locks(authentication.access_token)

front_lock_status = api.get_lock_status(authentication.access_token,'BF4F854D9E9B4786A9FA3A8833AAE09A')
front_door_status = api.get_lock_door_status(authentication.access_token,'BF4F854D9E9B4786A9FA3A8833AAE09A')

back_lock_status = api.get_lock_status(authentication.access_token,'41C161F1D5DB4C30948CE8184C8438F1')
back_door_status = api.get_lock_door_status(authentication.access_token,'41C161F1D5DB4C30948CE8184C8438F1')



open = "LockDoorStatus.OPEN"
closed = "LockDoorStatus.CLOSED"


def frontDoorState():
    if str(front_door_status) == open:
        print(0)
    elif str(front_door_status) == closed:
        print(1)

frontDoorState()
```

![image](https://user-images.githubusercontent.com/15041304/57258096-9736fc80-7018-11e9-8ea0-258ff75cd2a1.png)

Here are some of the error logs I'm getting from homebridge:
```
0|homebridge  | [5/6/2019, 4:05:03 PM] [Cmd4] getGeneric StatusActive function for: Front Door cmd: python ~/.homebridge/Cmd4Scripts/front_door_state.py Get 'Front Door' 'StatusActive' failed.
0|homebridge  | [5/6/2019, 4:05:03 PM] [Cmd4] { Error: Command failed: python ~/.homebridge/Cmd4Scripts/front_door_state.py Get 'Front Door' 'StatusActive'
0|homebridge  |     at ChildProcess.exithandler (child_process.js:294:12)
0|homebridge  |     at ChildProcess.emit (events.js:189:13)
0|homebridge  |     at maybeClose (internal/child_process.js:970:16)
0|homebridge  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
0|homebridge  |   killed: true,
0|homebridge  |   code: null,
0|homebridge  |   signal: 'SIGTERM',
0|homebridge  |   cmd:
0|homebridge  |    'python ~/.homebridge/Cmd4Scripts/front_door_state.py Get \'Front Door\' \'StatusActive\'' }
0|homebridge  | [5/6/2019, 4:05:03 PM] [Cmd4]
0|homebridge  | [5/6/2019, 4:05:03 PM] [Cmd4]
0|homebridge  | [5/6/2019, 4:05:13 PM] [Cmd4] getGeneric StatusFault function for: Front Door cmd: python ~/.homebridge/Cmd4Scripts/front_door_state.py Get 'Front Door' 'StatusFault' failed.
0|homebridge  | [5/6/2019, 4:05:13 PM] [Cmd4] { Error: Command failed: python ~/.homebridge/Cmd4Scripts/front_door_state.py Get 'Front Door' 'StatusFault'
0|homebridge  |     at ChildProcess.exithandler (child_process.js:294:12)
0|homebridge  |     at ChildProcess.emit (events.js:189:13)
0|homebridge  |     at maybeClose (internal/child_process.js:970:16)
0|homebridge  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
0|homebridge  |   killed: true,
0|homebridge  |   code: null,
0|homebridge  |   signal: 'SIGTERM',
0|homebridge  |   cmd:
0|homebridge  |    'python ~/.homebridge/Cmd4Scripts/front_door_state.py Get \'Front Door\' \'StatusFault\'' }
0|homebridge  | [5/6/2019, 4:05:13 PM] [Cmd4]
0|homebridge  | [5/6/2019, 4:05:13 PM] [Cmd4]
0|homebridge  | [5/6/2019, 4:06:03 PM] [Cmd4] getGeneric StatusFault function for: Front Door cmd: python ~/.homebridge/Cmd4Scripts/front_door_state.py Get 'Front Door' 'StatusFault' failed.
0|homebridge  | [5/6/2019, 4:06:03 PM] [Cmd4] { Error: Command failed: python ~/.homebridge/Cmd4Scripts/front_door_state.py Get 'Front Door' 'StatusFault'
0|homebridge  |     at ChildProcess.exithandler (child_process.js:294:12)
0|homebridge  |     at ChildProcess.emit (events.js:189:13)
0|homebridge  |     at maybeClose (internal/child_process.js:970:16)
0|homebridge  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
0|homebridge  |   killed: true,
0|homebridge  |   code: null,
0|homebridge  |   signal: 'SIGTERM',
0|homebridge  |   cmd:
0|homebridge  |    'python ~/.homebridge/Cmd4Scripts/front_door_state.py Get \'Front Door\' \'StatusFault\'' }
0|homebridge  | [5/6/2019, 4:06:03 PM] [Cmd4]
0|homebridge  | [5/6/2019, 4:06:03 PM] [Cmd4]
```

**Comment by rykermorgan** [comment]
Suddenly it's working. Seems like maybe it was having trouble with the py-august auth, since the log shows the command itself was failing.

Closing

**Comment by ztalbot2000** [comment]
Hi,

  I'm glad you got it working.  I was just starting to look at your
problem.  If I can help further, please let me know.

John Talbot

**Comment by ztalbot2000** [comment]
Any script should have an exit status.  I'm not sure if I see that in yours.

TTFN,
John

**Comment by rykermorgan** [comment]
What would be the best way to implement that?

I’ve tried a couple of things, but end up with the same error.

-- 
Ryker Morgan

**Comment by ztalbot2000** [comment]
Hi Ryker,

   I do believe, the problem is the tilda slash.  Running it from the
command line works because your shell expands it.  You should remove this
from your config.json file.
When Homebridge is run from a cron or daemon, it will naturally find the
.homebridge path from that users home directory.

Please also send me your script file if this does not fix things for you.
John
