### ISSUE TITLE
The requested platform 'config' was not registered by any plugin.

### ISSUE THREAD

**Issue by frogcjn** [ztalbot2000/homebridge-cmd4#3]
The requested platform 'config' was not registered by any plugin.

**Comment by ztalbot2000** [comment]
Did you miss step 2?  -> npm install -g homebridge-cmd4
Please post the exact command and output you were seeing when the problem occurred. Thanks

**Comment by frogcjn** [comment]
I have not missed step 2. And I'm running homebridge on macOS.
```
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by ztalbot2000** [comment]
I run on a MAC as well.  The very top says that homebridge-cmd4 was loaded successfully.  There seems to be something else in your $home/.homebridge/config.json file that is causing the problem.  If you load the default config.json file that comes with homebridge-cmd4 you can see if my addon is the problem, but it does not appear to be so from your log.  If you like, you can send me yours at: z t a l b o t 2 0 0 0 @gmail.com and I will see what I can find. (My email is slightly obfuscated to stop bots)

**Comment by ztalbot2000** [comment]
Actually you can see that it failed to load BLE module, not home bridge-cmd4
