### ISSUE TITLE
/usr/lib/node_modules/homebridge-cmd4/index.js:1354

### ISSUE THREAD

**Issue by thuongtin** [ztalbot2000/homebridge-cmd4#8]
/usr/lib/node_modules/homebridge-cmd4/index.js:1354
                  if (characteristicStrincharacteristicString == "TargetTemperature")
                  ^

ReferenceError: characteristicStrincharacteristicString is not defined
    at /usr/lib/node_modules/homebridge-cmd4/index.js:1354:19
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by ztalbot2000** [comment]
Thanks for the traceback.  ill fix the typo

**Comment by ztalbot2000** [comment]
Updated
